import type {Metadata} from 'next';
import Link from 'next/link';
import {notFound} from 'next/navigation';
import {Action,TextLink,Label,InternalHero,SectionHeading,Closing,Icon} from '@/components/ui';
import {ContactForm} from '@/components/contact-form';
import {InsightsList} from '@/components/insights-list';
import {services,archive} from '@/content/site';
import {pl} from '@/content/pl';

type Props={params:Promise<{slug:string}>};
const keys=Object.keys(pl.pages);
export function generateStaticParams(){return keys.map(slug=>({slug}));}
export async function generateMetadata({params}:Props):Promise<Metadata>{const{slug}=await params;const page=pl.pages[slug as keyof typeof pl.pages];return page?{title:page.title,description:page.description,alternates:{canonical:`/pl/${slug}`}}:{}}
function ProcessBand(){return <section className="section process-section"><div className="container"><SectionHeading label="Jak działamy" title={<>Od celu do działania.</>} description="Zaczynamy od kontekstu Twojego biznesu i skupiamy się na relacjach, które mogą pomóc w jego rozwoju."/><div className="process-line" data-line/><div className="process-grid">{pl.process.map((p,i)=><article className="process-step" key={p.name} data-reveal><span className="process-number">0{i+1}</span><h3>{p.name}</h3><p>{p.text}</p></article>)}</div></div></section>}
function PolishClosing({title='Porozmawiajmy o biznesie.',text='Opowiedz nam, co chcesz osiągnąć w Polsce, Izraelu lub na obu rynkach.',button='Rozpocznij rozmowę'}:{title?:string;text?:string;button?:string}){return <Closing title={title} text={text} button={button} label="Kolejny krok" href="/pl/contact"/>}

export default async function PolishInternalPage({params}:Props){
 const{slug}=await params;
 if(!keys.includes(slug))notFound();
 if(slug==='what-we-do')return <><InternalHero label="Co robimy" title={<>Twój cel.<br/>Właściwe kontakty.</>} text="Praktyczne wsparcie dla firm i organizacji, które chcą rozwijać relacje biznesowe między Polską a Izraelem."/><section className="section"><div className="container"><div className="lead-layout" data-reveal><h2>Wsparcie dopasowane<br/>do potrzeb Twojej firmy.</h2><div className="lead-copy"><p>Nasze działania wynikają z konkretnego celu zapytania, a nie z uniwersalnego modelu obsługi.</p><p>Od pierwszej rozmowy o rynku po ukierunkowaną misję gospodarczą pomagamy znaleźć właściwe osoby, organizacje i możliwości.</p></div></div></div></section><section className="section slim-section"><div className="container"><div className="service-grid">{services.map((s,i)=><article className="service-card" id={s.id} key={s.id} data-reveal><div className="card-top"><span>0{i+1}</span><Icon name={s.icon}/></div><h3>{pl.services[i].name}</h3><p>{pl.services[i].text}</p><TextLink href={`/pl/contact?topic=${encodeURIComponent(pl.services[i].topic)}`}>Opowiedz nam o swoim celu</TextLink></article>)}</div></div></section><ProcessBand/><PolishClosing title="Co chcesz osiągnąć?" text="Opowiedz nam o swoim celu biznesowym, rynku i kontaktach, których szukasz." button="Rozpocznij rozmowę"/></>;
 if(slug==='poland-israel')return <><InternalHero label="Polska ↔ Izrael" title={<>Dwa rynki.<br/>Jeden biznesowy most.</>} text="PICC pomaga rozwijać współpracę biznesową między Polską a Izraelem w sposób praktyczny, dostępny i oparty na relacjach."/><section className="section"><div className="container"><SectionHeading label="Uzupełniające się perspektywy" title={<>Warto połączyć te rynki.</>} description="Polska i Izrael oferują różne, lecz uzupełniające się możliwości, kształtowane przez firmy, przedsiębiorczość i międzynarodowe relacje."/><div className="market-panels"><article className="country-panel" data-reveal><span className="country-code" aria-hidden="true">PL</span><Label>Polska</Label><h3>Możliwości handlowe.<br/>Nowe partnerstwa.</h3><p>Rynek dla izraelskich firm poszukujących możliwości handlowych, partnerstw, inwestycji i rozwoju.</p><TextLink href="/pl/contact?topic=Market%20Entry">Poznaj możliwości w Polsce</TextLink></article><article className="country-panel" data-reveal><span className="country-code" aria-hidden="true">IL</span><Label>Izrael</Label><h3>Pomysły. Technologie.<br/>Kontakty biznesowe.</h3><p>Rynek dla polskich firm szukających technologii, innowacji, inwestycji, partnerstw i możliwości międzynarodowych.</p><TextLink href="/pl/contact?topic=Market%20Entry">Poznaj możliwości w Izraelu</TextLink></article></div></div></section><section className="section why-section"><div className="container lead-layout"><div data-reveal><Label>PICC jako łącznik</Label><h2>Od zainteresowania<br/>do rzeczowego dialogu.</h2></div><div className="lead-copy" data-reveal><p>PICC tworzy platformę, na której firmy i organizacje mogą poznawać możliwości i rozwijać praktyczną współpracę.</p><p>Ułatwiamy relacje, które pomagają przejść od zainteresowania do rozmowy, a tam, gdzie to możliwe, od rozmowy do wspólnego działania.</p><div className="actions"><Action href="/pl/what-we-do">Jak możemy pomóc</Action></div></div></div></section><PolishClosing/></>;
 if(slug==='about')return <><InternalHero label="O PICC" title={<>Przedsiębiorcy.<br/>Wspólne możliwości.</>} text="Izba gospodarcza o praktycznym celu: pomagamy firmom budować relacje i rozwijać możliwości między Polską a Izraelem." photo photoAsset="grafika" photoAlt="Dostarczona grafika PICC: monochromatyczna scena na dachu z panoramą miasta i czerwono-niebieską geometrią; zdjęcie Ela Sheran."/><section className="section"><div className="container lead-layout"><div data-reveal><Label>Nasza rola</Label><h2>Platforma<br/>współpracy.</h2></div><div className="lead-copy" data-reveal><p>Polsko-Izraelska Izba Gospodarcza wspiera kontakty handlowe między Polską a Izraelem i pomaga firmom tworzyć nowe możliwości biznesowe oraz rozwijać działalność.</p><p>Łączymy relacje biznesowe, wiedzę i współpracę instytucjonalną, ułatwiając praktyczne działania transgraniczne.</p></div></div></section><section className="section why-section"><div className="container"><SectionHeading label="Nasza misja" title={<>Łączymy. Rozwijamy. Wspieramy.</>} description="Wspieramy polskie i izraelskie firmy oraz przedsiębiorców w realizacji innowacyjnych projektów, rozwijaniu możliwości biznesowych i poruszaniu się na obu rynkach."/><div className="pillar-grid">{[['Łączymy','network','Budujemy wartościowe relacje między firmami i organizacjami.'],['Rozwijamy','growth','Wspieramy nowe możliwości biznesowe i współpracę międzynarodową.'],['Wspieramy','bridge','Ułatwiamy dostęp do osób, wiedzy i kontaktów instytucjonalnych.']].map(([title,icon,text],i)=><article className="pillar" key={title} data-reveal><div className="pillar-top"><span>0{i+1}</span><Icon name={icon}/></div><h3>{title}</h3><p>{text}</p></article>)}</div></div></section><section className="section"><div className="container"><div className="history-block"><div className="history-year" data-reveal>2016<span>POWSTANIE W SIERPNIU</span></div><div data-reveal><h3>Izba założona przez przedsiębiorców.</h3><p>PICC powstała w sierpniu 2016 roku w odpowiedzi na potrzeby środowiska biznesowego i rozwój wymiany gospodarczej między Polską a Izraelem.</p><p>Założyciele dostrzegli znaczenie doświadczenia, wiedzy i zaufanych relacji w budowaniu udanej współpracy biznesowej.</p></div></div></div></section><PolishClosing/></>;
 if(slug==='network')return <><InternalHero label="Nasza sieć" title={<>Relacje, które<br/>otwierają możliwości.</>} text="Sieć PICC łączy firmy, przedsiębiorców, inwestorów, uczelnie i organizacje zaangażowane we współpracę polsko-izraelską."/><section className="section"><div className="container"><SectionHeading label="Kogo łączymy" title={<>W całym ekosystemie biznesu.</>} description="Skuteczna współpraca międzynarodowa wymaga relacji w biznesie, nauce i instytucjach."/><div className="network-list">{pl.audiences.map((a,i)=><article key={a.name} className="network-item" data-reveal><div><Icon name={['services','mission','growth','consulting','institution'][i]}/><h3>{a.name}</h3></div><p>{a.text}</p></article>)}</div></div></section><PolishClosing title="Szukasz właściwego kontaktu?" text="Opowiedz nam o firmie, branży lub relacji, której szukasz."/></>;
 if(slug==='startups')return <><InternalHero label="Startupy i innowacje" title={<>Łączymy innowacje<br/>ponad granicami.</>} text="Innowacje rozwijają się dzięki wymianie pomysłów, wiedzy, kapitału i dostępowi do rynku. PICC wspiera startupy i innowacyjne firmy budujące relacje między Polską a Izraelem." photo/><section className="section"><div className="container"><SectionHeading label="Obszary wsparcia" title={<>Pomysł otwiera<br/>nową rozmowę.</>} description="W zależności od celu możemy pomóc w nawiązaniu kontaktów, udziale w wydarzeniach tematycznych i odkrywaniu możliwości rozwoju międzynarodowego."/><div className="innovation-support">{pl.innovation.map(([title,text,icon])=><article key={title} data-reveal><Icon name={icon}/><h3>{title}</h3><p>{text}</p></article>)}</div></div></section><ProcessBand/><PolishClosing title="Opowiedz nam, co tworzysz." text="Napisz o projekcie, interesującym Cię rynku i rodzaju relacji, którą chcesz rozwinąć." button="Opowiedz o projekcie"/></>;
 if(slug==='insights')return <><InternalHero label="Wydarzenia i analizy" title={<>Wspólne perspektywy.<br/>Nowe kontakty.</>} text="Spotkania biznesowe, networking, wydarzenia tematyczne, inicjatywy międzynarodowe i misje gospodarcze łączące Polskę z Izraelem."/><section className="section"><div className="container"><InsightsList polish/><div className="content-bottom" data-reveal><div><h3>Chcesz porozmawiać o przyszłej współpracy?</h3><p>Skontaktuj się z PICC w sprawie spotkań biznesowych, wydarzeń tematycznych lub inicjatyw międzynarodowych dopasowanych do Twojego celu.</p></div><Action href="/pl/contact">Kontakt z PICC</Action></div></div></section></>;
 if(slug==='contact')return <><InternalHero label="Kontakt z PICC" title={<>Porozmawiajmy<br/>o biznesie.</>} text={pl.contact.intro}/><section className="section"><div className="container contact-layout"><aside className="contact-sidebar" data-reveal="left"><Label>{pl.contact.sidebar}</Label><h2>{pl.contact.sidebarTitle}</h2><p style={{marginBottom:30,fontSize:15}}>{pl.contact.sidebarText}</p><div className="contact-detail"><Icon name="mail"/><div><h3>{pl.contact.emailUs}</h3><a href="mailto:office@polishisraeli.org">office@polishisraeli.org</a></div></div><div className="contact-detail"><Icon name="pin"/><div><h3>{pl.contact.office}</h3><p>Polsko-Izraelska Izba Gospodarcza<br/>ul. Trębacka 4<br/>00-074 Warszawa, Polska</p></div></div></aside><ContactForm polish/></div></section></>;
 if(['privacy','gdpr','cookies'].includes(slug)){const cookie=slug==='cookies';return <><InternalHero label="Informacje o stronie" title={pl.pages[slug as keyof typeof pl.pages].title} text="Ta strona jest wersją roboczą do weryfikacji. Przed publikacją zostaną dodane zatwierdzone informacje PICC."/><section className="section"><div className="container legal-layout"><h2>{cookie?'Pliki cookie w wersji roboczej':'Twoje dane w wersji roboczej'}</h2><p>{cookie?'Ta wersja nie zawiera narzędzi reklamowych, analityki ani opcjonalnych plików śledzących. Czcionki i obrazy są dostarczane razem ze stroną.':'Podgląd formularza działa lokalnie w przeglądarce. Wpisane dane nie są wysyłane do PICC ani zapisywane przez formularz. Odświeżenie lub opuszczenie strony usuwa podgląd.'}</p><h2>Przed uruchomieniem</h2><p>{cookie?'Końcowa informacja o plikach cookie będzie odzwierciedlać usługi używane przez opublikowaną stronę.':'Należy dodać zatwierdzone informacje o administratorze danych, celach i podstawach przetwarzania, okresie przechowywania oraz prawach użytkowników.'}</p><p>W sprawie zapytania biznesowego możesz napisać na adres <a href="mailto:office@polishisraeli.org">office@polishisraeli.org</a>.</p><TextLink href="/pl/contact">Przejdź do kontaktu</TextLink></div></section></>}
 if(slug==='preview-notes')return <><InternalHero label="PICC / Wersja do weryfikacji" title={<>Opracowana zgodnie<br/>z ustalonym kierunkiem.</>} text="Informacje o wykorzystanych materiałach, decyzjach projektowych i elementach do uzupełnienia przed uruchomieniem strony."/><section className="section"><div className="container legal-layout"><h2>Wykorzystane materiały</h2><ul className="notes-list"><li>Specyfikacja strony PICC w języku angielskim: struktura, treści, usługi, formularz i wytyczne marki.</li><li>Logo PICC oraz grafiki 2.jpg i Grafika_1.jpg: kształt znaku, fotografia monochromatyczna i geometryczne nakładki kolorystyczne.</li><li>Materiały badawcze i zatwierdzony kierunek wizualny oraz makiety.</li></ul><h2>Elementy do zatwierdzenia przed publikacją</h2><ul className="notes-list"><li>Polska wersja językowa jest kompletna i oczekuje na końcową weryfikację językową PICC.</li><li>Formularz jest podglądem lokalnym; przed publikacją wymaga bezpiecznej wysyłki, walidacji po stronie serwera i ochrony przed spamem.</li><li>Adres e-mail i adres biura należy potwierdzić; numer telefonu wymaga weryfikacji.</li><li>Ikony społecznościowe w stopce są ukryte do czasu potwierdzenia aktywnych profili PICC.</li><li>Aktualne relacje instytucjonalne, członkowie zarządu, wydarzenia i programy startupowe wymagają zatwierdzenia.</li><li>Końcowe teksty prawne oraz domenę własną należy skonfigurować przed publikacją.</li></ul><h2>Wydarzenie archiwalne</h2><p>Nota opisuje forum z 19 czerwca 2018 roku na podstawie relacji opublikowanej przez polski rząd 20 czerwca 2018 roku. Nie przedstawia wydarzenia jako aktualnego ani nie potwierdza obecnego statusu współpracy instytucjonalnej.</p><a className="source-link" href={archive.source} target="_blank" rel="noreferrer">Przeczytaj źródło rządowe</a></div></section></>;
 return null;
}
