import type {Metadata} from 'next';
import Link from 'next/link';
import {Action,TextLink,Label,Photo,Icon,SectionHeading,Closing} from '@/components/ui';
import {services} from '@/content/site';
import {pl} from '@/content/pl';

export const metadata:Metadata={
 title:'Polsko-Izraelska Izba Gospodarcza | Biznes między Polską a Izraelem',
 description:'PICC łączy firmy, przedsiębiorców, inwestorów i instytucje z Polski i Izraela, wspierając partnerstwa biznesowe, projekty międzynarodowe i współpracę transgraniczną.',
 alternates:{canonical:'/pl'},
};

const why=[
 ['Wiedza','globe','Znajomość polskiego i izraelskiego środowiska biznesowego oraz kontekstu działania firm.'],
 ['Kontakty','network','Relacje z firmami, startupami, inwestorami, środowiskiem akademickim i instytucjami.'],
 ['Wsparcie','bridge','Praktyczna pomoc w nawiązywaniu kontaktów, organizacji spotkań i rozwijaniu współpracy międzynarodowej.'],
];

export default function PolishHome(){return <>
 <section className="home-hero"><div className="hero-copy" data-reveal="left"><Label>{pl.home.eyebrow}</Label><h1>{pl.home.title}</h1><p>{pl.home.intro}</p><div className="actions"><Action href="/pl/contact">{pl.home.cta}</Action><TextLink href="/pl/what-we-do">{pl.home.whatWeDo}</TextLink></div><div className="hero-bridge"><div><b>{pl.home.countries[0]}</b><span>Biznes i możliwości</span></div><i aria-hidden="true"/><div><b>{pl.home.countries[1]}</b><span>Kontakty i współpraca</span></div></div></div><Photo priority className="hero-photo" caption="Wspólna perspektywa. Nowe możliwości." motion="scale" alt="Monochromatyczna ilustracja architektury biznesowej z geometrycznym motywem PICC"/><a className="hero-scroll" href="#introduction"><span>{pl.home.discover}</span><Icon name="arrow-up"/></a></section>
 <section className="introduction container" id="introduction"><div data-reveal><Label number="01">{pl.home.introLabel}</Label></div><div data-reveal><h2>{pl.home.introTitle}</h2><p>{pl.home.introText}</p><TextLink href="/pl/about">{pl.home.meet}</TextLink></div></section>
 <section className="section services-section" id="services"><div className="container services-layout"><div className="services-heading" data-reveal><Label number="02">{pl.home.servicesLabel}</Label><h2>{pl.home.servicesTitle}</h2><p>{pl.home.servicesText}</p><TextLink href="/pl/what-we-do">{pl.home.exploreServices}</TextLink></div><div className="service-rows">{services.map((s,i)=><Link href={`/pl/what-we-do#${s.id}`} className="service-row" key={s.id} data-reveal><span className="service-index">0{i+1}</span><div><h3>{pl.services[i].name}</h3><p>{pl.services[i].short}</p></div><Icon name={s.icon} className="service-symbol"/><Icon name="arrow-up-right" className="row-arrow"/></Link>)}</div></div></section>
 <section className="section why-section home-why"><div className="container"><SectionHeading number="03" label={pl.home.whyLabel} title={pl.home.whyTitle} description={pl.home.whyText}/><div className="pillar-grid">{why.map(([title,icon,text],i)=><article className="pillar" key={title} data-reveal><div className="pillar-top"><span>0{i+1}</span><Icon name={icon}/></div><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
 <section className="market-section"><div className="market-visual" data-reveal><Photo className="market-photo" original parallax={false} alt="Dostarczona grafika PICC: architektura miejska z biało-czarnym zdjęciem i czerwono-niebieską geometrią"/><div className="market-caption"><span>POLSKA</span><i/><span>IZRAEL</span></div></div><div className="market-copy" data-reveal><Label number="04">{pl.home.marketLabel}</Label><h2>{pl.home.marketTitle}</h2><p>{pl.home.marketText}</p><Action href="/pl/poland-israel" light>{pl.home.marketCta}</Action></div></section>
 <section className="section audiences-section"><div className="container"><SectionHeading number="05" label={pl.home.audienceLabel} title={pl.home.audienceTitle} description={pl.home.audienceText}/><div className="audience-grid">{pl.audiences.map((a,i)=><Link href={a.name==='Startupy'?'/pl/startups':'/pl/network'} className="audience-card" key={a.name} data-reveal><span className="audience-num">0{i+1}</span><Icon name={['services','mission','growth','consulting','institution'][i]}/><h3>{a.name}</h3><p>{a.text}</p><Icon name="arrow-up-right" className="audience-arrow"/></Link>)}</div></div></section>
 <section className="section process-section"><div className="container"><SectionHeading number="06" label={pl.home.processLabel} title={pl.home.processTitle} description={pl.home.processText}/><div className="process-line" data-line/><div className="process-grid">{pl.process.map((p,i)=><article key={p.name} className="process-step" data-reveal><span className="process-number">0{i+1}</span><h3>{p.name}</h3><p>{p.text}</p></article>)}</div></div></section>
 <section className="section innovation-section"><div className="container innovation-layout"><div className="innovation-visual" data-reveal><Photo className="innovation-photo" alt="Monochromatyczna ilustracja nowoczesnej dzielnicy biznesowej" parallax={false}/></div><div className="innovation-copy" data-reveal><Label number="07">{pl.home.innovationLabel}</Label><h2>{pl.home.innovationTitle}</h2><p>{pl.home.innovationText}</p><ul className="check-list">{pl.innovation.map(([title],i)=><li key={title}>{title}</li>)}</ul><Action href="/pl/contact?topic=Startup%20%2F%20Innovation">{pl.home.innovationCta}</Action><TextLink href="/pl/startups">{pl.home.startupPage}</TextLink></div></div></section>
 <section className="network-strip"><div className="container network-strip-inner"><div data-reveal><Label number="08">{pl.home.networkLabel}</Label><h2>{pl.home.networkTitle}</h2></div><div data-reveal><p>{pl.home.networkText}</p><TextLink href="/pl/network">{pl.home.networkCta}</TextLink></div><div className="network-symbol" aria-hidden="true"><Icon name="network"/></div></div></section>
 <section className="section insights-preview"><div className="container"><SectionHeading number="09" label={pl.home.insightsLabel} title={pl.home.insightsTitle} description={pl.home.insightsText}/><div className="section-bottom-link"><TextLink href="/pl/insights">{pl.home.insightsCta}</TextLink></div></div></section>
 <Closing title={pl.home.closeTitle} text={pl.home.closeText} button={pl.home.closeCta} label="Kolejny krok" href="/pl/contact"/>
</>}
