export const pl = {
  nav: {
    home: 'Strona główna', whatWeDo: 'Co robimy', polandIsrael: 'Polska ↔ Izrael', about: 'O PICC',
    network: 'Sieć kontaktów', insights: 'Wydarzenia i analizy', contact: 'Kontakt', talk: 'Porozmawiajmy',
    explore: 'Nawigacja', discover: 'Poznaj PICC', connect: 'Skontaktuj się z nami',
  },
  home: {
    eyebrow: 'Polsko-Izraelska Izba Gospodarcza',
    title: <>Łączymy biznes<br/>między <span>Polską</span><br/>a <span>Izraelem.</span></>,
    intro: 'Łączymy firmy, przedsiębiorców, inwestorów i instytucje na dwóch rynkach, pomagając budować relacje, dostrzegać możliwości i rozwijać współpracę międzynarodową.',
    cta: 'Porozmawiajmy', whatWeDo: 'Co robimy', discover: 'Poznaj PICC',
    countries: ['POLSKA', 'IZRAEL'],
    introLabel: 'Platforma dla biznesu',
    introTitle: <>Dwa rynki biznesowe.<br/><span className="muted">Wspólne możliwości.</span></>,
    introText: 'Polsko-Izraelska Izba Gospodarcza wspiera kontakty handlowe i rozwój współpracy gospodarczej między Polską a Izraelem. PICC powstała z inicjatywy przedsiębiorców i łączy doświadczenie, wiedzę oraz relacje biznesowe, aby pomagać firmom znajdować partnerów, rozwijać możliwości i budować współpracę międzynarodową. Działamy praktycznie: poznajemy cel, rozumiemy kontekst biznesowy i pomagamy nawiązać właściwe kontakty.',
    meet: 'Poznaj PICC', servicesLabel: 'Co robimy', servicesTitle: <>Od celu biznesowego<br/>do <span className="blue-text">możliwości.</span></>,
    servicesText: 'Międzynarodowy biznes wymaga właściwych relacji, znajomości lokalnego rynku i dostępu do odpowiednich osób. PICC oferuje praktyczne wsparcie dopasowane do indywidualnych celów firm i przedsiębiorców.',
    exploreServices: 'Poznaj nasze usługi', whyLabel: 'Dlaczego PICC', whyTitle: <>Właściwy kontekst.<br/>Właściwe kontakty.</>,
    whyText: 'Udana współpraca międzynarodowa opiera się na zrozumieniu, relacjach i umiejętności przekuwania rozmów w konkretne działania.',
    marketLabel: 'Polska ↔ Izrael', marketTitle: <>Dwa rynki.<br/>Jeden biznesowy<br/>most.</>,
    marketText: 'Polska i Izrael oferują różne, lecz uzupełniające się środowiska biznesowe, kształtowane przez przedsiębiorczość, technologię i międzynarodowe powiązania. PICC pomaga zamieniać zainteresowanie współpracą w rzeczowy dialog i, tam gdzie to możliwe, wspólne działania.',
    marketCta: 'Poznaj oba rynki', audienceLabel: 'Z kim współpracujemy', audienceTitle: <>Ekosystem<br/>pełen możliwości.</>,
    audienceText: 'Skuteczna współpraca łączy różne obszary wiedzy i doświadczenia. Współpracujemy z organizacjami i osobami, które rozwijają kontakty między rynkami.',
    processLabel: 'Jak działamy', processTitle: <>Od celu<br/>do działania.</>,
    processText: 'Każde zapytanie ma swój kontekst. Zaczynamy od rozmowy, a następnie skupiamy się na osobach i możliwościach najlepiej dopasowanych do celu.',
    innovationLabel: 'Innowacje i startupy', innovationTitle: <>Łączymy innowacje<br/><span className="blue-text">ponad granicami.</span></>,
    innovationText: 'Rozwój innowacji wymaga wymiany pomysłów, wiedzy, kapitału i dostępu do rynku. PICC wspiera startupy i innowacyjne firmy, które chcą budować relacje biznesowe między Polską a Izraelem.',
    innovationCta: 'Opowiedz o swoim projekcie', startupPage: 'Wsparcie dla startupów',
    networkLabel: 'Nasza sieć', networkTitle: <>Sieć oparta<br/>na współpracy.</>,
    networkText: 'PICC łączy biznes, inwestorów, środowisko akademickie i instytucje, wspierając współpracę międzynarodową.',
    networkCta: 'Poznaj naszą sieć', insightsLabel: 'Wydarzenia i analizy',
    insightsTitle: <>Kontakty<br/>w praktyce.</>,
    insightsText: 'Spotkania biznesowe, inicjatywy międzynarodowe i perspektywy dotyczące współpracy polsko-izraelskiej.',
    insightsCta: 'Zobacz wydarzenia i analizy', closeTitle: 'Porozmawiajmy o biznesie.',
    closeText: 'Powiedz nam, co chcesz osiągnąć w Polsce, Izraelu lub na obu rynkach.', closeCta: 'Rozpocznij rozmowę',
  },
  services: [
    { name: 'Doradztwo biznesowe', short: 'Lokalna wiedza, która wspiera decyzje biznesowe.', text: 'Praktyczne wskazówki dla firm rozważających możliwości, partnerstwa lub rozwój na rynkach polskim i izraelskim.', topic: 'Market Entry' },
    { name: 'Partnerzy biznesowi', short: 'Znajdź osoby i organizacje dopasowane do swojego celu.', text: 'Identyfikacja potencjalnych firm i organizacji odpowiadających konkretnemu celowi biznesowemu.', topic: 'Business Partner Search' },
    { name: 'Spotkania biznesowe', short: 'Stwórz warunki do wartościowej rozmowy.', text: 'Organizacja spotkań i przedstawień między właściwymi osobami decyzyjnymi.', topic: 'Business Meeting' },
    { name: 'Misje gospodarcze', short: 'Poznaj rynek dzięki dobrze zaplanowanym kontaktom.', text: 'Planowanie i wsparcie misji gospodarczych i handlowych, które łączą firmy z odpowiednim środowiskiem rynkowym.', topic: 'Business Mission' },
    { name: 'Projekty międzynarodowe', short: 'Rozwijaj współpracę firm i instytucji.', text: 'Wsparcie w nawiązywaniu współpracy w ramach projektów międzynarodowych z udziałem polskich i izraelskich partnerów.', topic: 'International Project' },
    { name: 'Wsparcie prawne', short: 'Dostęp do pomocy prawnej w działalności międzynarodowej.', text: 'Dostęp do kontaktów prawnych i wsparcia związanego z działalnością międzynarodową.', topic: 'Legal Support' },
  ],
  audiences: [
    { name: 'Firmy', text: 'Przedsiębiorstwa rozwijające partnerstwa, działalność międzynarodową i nowe możliwości rynkowe.' },
    { name: 'Startupy', text: 'Innowacyjne firmy poszukujące międzynarodowych kontaktów, partnerów, inwestorów i możliwości rozwoju.' },
    { name: 'Inwestorzy', text: 'Fundusze, inwestorzy prywatni, aniołowie biznesu, banki i instytucje finansowe zainteresowane biznesem i innowacjami.' },
    { name: 'Środowisko akademickie', text: 'Uczelnie i ośrodki badawcze wspierające wymianę wiedzy, innowacje i rozwój technologii.' },
    { name: 'Instytucje', text: 'Ambasady, izby gospodarcze i inne organizacje wspierające współpracę gospodarczą.' },
  ],
  process: [
    { name: 'Poznajemy cel', text: 'Poznajemy cel biznesowy, rynek docelowy, branżę oraz rodzaj relacji, którą chcesz rozwinąć.' },
    { name: 'Szukamy możliwości', text: 'Wskazujemy firmy, przedsiębiorców, inwestorów, instytucje i ekspertów, którzy mogą odpowiadać Twoim potrzebom.' },
    { name: 'Łączymy', text: 'Ułatwiamy nawiązywanie kontaktów i pomagamy stworzyć właściwe warunki do rozmowy biznesowej.' },
    { name: 'Rozwijamy współpracę', text: 'Tam, gdzie to uzasadnione, wspieramy rozwój relacji w kierunku nowej możliwości, projektu lub współpracy międzynarodowej.' },
  ],
  innovation: [
    ['Kontakty międzynarodowe', 'Przedstawienia firmom, instytucjom i organizacjom pozarządowym.', 'network'],
    ['Kontakty z inwestorami', 'Możliwości nawiązania relacji z funduszami, inwestorami prywatnymi i aniołami biznesu.', 'growth'],
    ['Rozwój na rynkach', 'Wsparcie w odkrywaniu możliwości międzynarodowego rozwoju biznesu.', 'globe'],
    ['Badania i technologie', 'Kontakty z instytucjami badawczymi oraz organizacjami rozwijającymi innowacje i technologie.', 'layers'],
    ['Wydarzenia i promocja', 'Udział w tematycznych wydarzeniach i wybrane możliwości prezentacji projektów oraz wiedzy.', 'insights'],
    ['Informacje specjalistyczne', 'Dostęp do przydatnych informacji rynkowych i kontaktów eksperckich.', 'consulting'],
  ],
  insights: {
    categories: ['Wszystkie', 'Biznes', 'Innowacje', 'Wydarzenia', 'Startupy'],
    title: 'Polsko-Izraelskie Forum Gospodarcze',
    excerpt: 'Spotkanie polskich i izraelskich firm poświęcone nawiązywaniu kontaktów i bezpośrednim rozmowom biznesowym.',
    archive: 'Z ARCHIWUM', place: 'TEL AWIW, IZRAEL', past: 'Wydarzenie archiwalne',
    empty: 'Więcej materiałów wkrótce.',
  },
  contact: {
    title: 'Porozmawiajmy o biznesie.',
    intro: 'Każdy cel biznesowy jest inny. Opowiedz nam, co chcesz osiągnąć w Polsce, Izraelu lub na obu rynkach, oraz podaj kontekst, który pozwoli nam zrozumieć Twoje zapytanie.',
    heading: 'Twój cel biznesowy', required: '* Pola wymagane',
    titleField: 'Tytuł', selectTitle: 'Wybierz tytuł', firstName: 'Imię', lastName: 'Nazwisko', company: 'Firma', position: 'Stanowisko', email: 'Adres e-mail', phone: 'Telefon', country: 'Kraj', topic: 'W czym możemy pomóc?', selectTopic: 'Wybierz obszar wsparcia', objective: 'Opowiedz nam o swoim celu biznesowym',
    placeholder: 'Opisz rynek, branżę i rodzaj kontaktu, którego szukasz…', consent: 'Wyrażam zgodę na kontakt w sprawie tego zapytania i zapoznałem(-am) się z informacją o prywatności.',
    previewNote: 'Podgląd wersji roboczej: formularz pozwala lokalnie sprawdzić treść zapytania. Dane nie są wysyłane ani zapisywane. Przed uruchomieniem zostaną dodane zatwierdzone informacje o prywatności i bezpieczna wysyłka wiadomości.',
    preview: 'Podgląd zapytania', sentTitle: 'Podgląd Twojego zapytania', notSent: 'Wiadomość nie została wysłana. Możesz edytować pola i ponownie wyświetlić podgląd.', name: 'Imię i nazwisko', area: 'Temat', unspecified: 'Nie określono',
    sidebar: 'Rozpocznij rozmowę', sidebarTitle: <>Kontakt to początek<br/>współpracy.</>, sidebarText: 'Podaj nam wystarczająco dużo informacji, abyśmy mogli zrozumieć Twoje zapytanie i planowaną relację biznesową.', emailUs: 'Napisz do nas', office: 'Biuro w Warszawie',
  },
  pages: {
    'what-we-do': { title: 'Co robimy', description: 'Praktyczne wsparcie w budowaniu relacji biznesowych między Polską a Izraelem, dopasowane do Twojego celu.' },
    'poland-israel': { title: 'Polska ↔ Izrael', description: 'Dwa rynki połączone relacjami biznesowymi, wiedzą i praktyczną współpracą.' },
    about: { title: 'O PICC', description: 'Poznaj Polsko-Izraelską Izbę Gospodarczą, jej misję i biznesowe początki.' },
    network: { title: 'Nasza sieć', description: 'Kontakty wśród firm, startupów, inwestorów, środowiska akademickiego i instytucji.' },
    startups: { title: 'Startupy i innowacje', description: 'Międzynarodowe kontakty dla innowacyjnych firm rozwijających współpracę między Polską a Izraelem.' },
    insights: { title: 'Wydarzenia i analizy', description: 'Spotkania biznesowe, inicjatywy międzynarodowe i perspektywy współpracy polsko-izraelskiej.' },
    contact: { title: 'Kontakt z PICC', description: 'Opowiedz nam o swoim celu biznesowym w Polsce, Izraelu lub na obu rynkach.' },
    privacy: { title: 'Polityka prywatności', description: 'Informacje o prywatności na stronie Polsko-Izraelskiej Izby Gospodarczej.' },
    gdpr: { title: 'Ochrona danych', description: 'Informacje dotyczące ochrony danych osobowych na stronie PICC.' },
    cookies: { title: 'Polityka plików cookie', description: 'Informacje o plikach cookie na stronie PICC.' },
    'preview-notes': { title: 'Informacje o wersji roboczej', description: 'Materiały źródłowe, decyzje projektowe i elementy do uzupełnienia przed uruchomieniem strony PICC.' },
  },
} as const;
