import Link from 'next/link';
import {Action,TextLink,Label,Photo,Icon,SectionHeading,Closing} from '@/components/ui';
import {services,audiences,process} from '@/content/site';

export default function Home(){return <>
 <section className="home-hero"><div className="hero-copy" data-reveal="left"><Label>Polish–Israeli Chamber of Commerce</Label><h1>Bridging Business<br/>Between <span>Poland</span><br/>and <span>Israel.</span></h1><p>Connecting companies, entrepreneurs, investors and institutions across two business environments, helping create relationships, identify opportunities and develop international cooperation.</p><div className="actions"><Action>Talk to Us</Action><TextLink href="/what-we-do">What We Do</TextLink></div><div className="hero-bridge"><div><b>POLAND</b><span>Business & opportunity</span></div><i aria-hidden="true"/><div><b>ISRAEL</b><span>Connections & cooperation</span></div></div></div><Photo priority className="hero-photo" caption="A shared perspective. New possibilities." motion="scale"/><a className="hero-scroll" href="#introduction"><span>Discover PICC</span><Icon name="arrow-up"/></a></section>
 <section className="introduction container" id="introduction"><div data-reveal><Label number="01">A business platform</Label></div><div data-reveal><h2>A Business Platform<br/><span className="muted">Connecting Two Markets</span></h2><p>The Polish–Israeli Chamber of Commerce is a platform supporting commercial contacts and the development of economic cooperation between Poland and Israel. Founded on the initiative of business people, PICC brings together experience, knowledge and business relationships to help companies identify partners, develop opportunities and build international cooperation. Our approach is practical: we listen to the objective, understand the business context and help connect the right people and organisations.</p><TextLink href="/about">Meet PICC</TextLink></div></section>
 <section className="section services-section" id="services"><div className="container services-layout"><div className="services-heading" data-reveal><Label number="02">What We Do</Label><h2>From business<br/>objective to<br/><span className="blue-text">opportunity.</span></h2><p>International business is built on more than information. It requires the right relationships, local understanding and access to relevant people. PICC supports companies and entrepreneurs with practical services designed around their individual objectives.</p><TextLink href="/what-we-do">Explore our services</TextLink></div><div className="service-rows">{services.map((s,i)=><Link href={`/what-we-do#${s.id}`} className="service-row" key={s.id} data-reveal><span className="service-index">0{i+1}</span><div><h3>{s.name}</h3><p>{i===0?'Practical support for companies exploring opportunities, partnerships and business development between Poland and Israel.':i===1?'Identification and introduction of relevant companies, entrepreneurs, investors and organisations based on a defined business objective.':s.short}</p></div><Icon name={s.icon} className="service-symbol"/><Icon name="arrow-up-right" className="row-arrow"/></Link>)}</div></div></section>
 <section className="section why-section home-why"><div className="container"><SectionHeading number="03" label="Why PICC" title={<>The right context.<br/>The right connections.</>} description="Successful international cooperation depends on understanding, relationships and the ability to turn a conversation into action."/><div className="pillar-grid">{[['Knowledge','globe','Understanding of the Polish and Israeli business environments and the context in which companies operate.'],['Connections','network','Relationships across companies, startups, investors, academia and institutions.'],['Facilitation','bridge','Practical support in establishing contacts, arranging meetings and developing international cooperation.']].map(([title,icon,text],i)=><article className="pillar" key={title} data-reveal><div className="pillar-top"><span>0{i+1}</span><Icon name={icon}/></div><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
 <section className="market-section"><div className="market-visual" data-reveal><Photo className="market-photo" original parallax={false} alt="Supplied PICC architectural artwork with monochrome photography and transparent red and blue geometry"/><div className="market-caption"><span>POLAND</span><i/><span>ISRAEL</span></div></div><div className="market-copy" data-reveal><Label number="04">Poland ↔ Israel</Label><h2>Two markets.<br/>One business<br/>bridge.</h2><p>Poland and Israel offer different but complementary business environments, shaped by their economic development, entrepreneurial communities, technology sectors and international connections.</p><p>PICC provides a platform through which companies and organisations can explore these connections and develop practical cooperation. We help relationships move from interest to meaningful dialogue and, where appropriate, from dialogue to cooperation.</p><Action href="/poland-israel" light>Explore the connection</Action></div></section>
 <section className="section audiences-section"><div className="container"><SectionHeading number="05" label="Who We Work With" title={<>An ecosystem<br/>of possibilities.</>} description="Effective international cooperation requires connections across different parts of the business ecosystem. PICC brings together organisations and professionals whose expertise, relationships and objectives can contribute to cross-border cooperation."/><div className="audience-grid">{audiences.map((a,i)=><Link href={a.name==='Startups'?'/startups':'/network'} className="audience-card" key={a.name} data-reveal><span className="audience-num">0{i+1}</span><Icon name={a.icon}/><h3>{a.name}</h3><p>{a.text}</p><Icon name="arrow-up-right" className="audience-arrow"/></Link>)}</div></div></section>
 <section className="section process-section"><div className="container"><SectionHeading number="06" label="How We Work" title={<>From objective<br/>to action.</>} description="Every enquiry has its own context. We begin by understanding your business objective, then focus on the people and opportunities that fit."/><div className="process-line" data-line/><div className="process-grid">{process.map((p,i)=><article key={p.name} className="process-step" data-reveal><span className="process-number">0{i+1}</span><h3>{p.name}</h3><p>{p.text}</p></article>)}</div></div></section>
 <section className="section innovation-section"><div className="container innovation-layout"><div className="innovation-visual" data-reveal><Photo className="innovation-photo" parallax={false}/></div><div className="innovation-copy" data-reveal><Label number="07">Innovation & Startups</Label><h2>Connecting<br/>innovation<br/><span className="blue-text">across borders.</span></h2><p>Innovation develops through the exchange of ideas, expertise, capital and market access. PICC supports startups and innovative companies interested in developing relationships between Poland and Israel.</p><ul className="check-list"><li>International connections — companies, institutions and NGOs</li><li>Investor networking — funds, private investors and business angels</li><li>Market development — international business opportunities</li><li>Research & technology — cooperation with research institutions</li><li>Events & visibility — thematic events and project presentations</li><li>Specialist information — relevant market knowledge and contacts</li></ul><Action href="/contact?topic=Startup%20%2F%20Innovation">Discuss your project</Action><TextLink href="/startups">Explore startup support</TextLink></div></div></section>
 <section className="network-strip"><div className="container network-strip-inner"><div data-reveal><Label number="08">Our Network</Label><h2>A network built<br/>around cooperation.</h2></div><div data-reveal><p>PICC works across business, investment, academia and institutions to facilitate international cooperation.</p><TextLink href="/network">Explore our network</TextLink></div><div className="network-symbol" aria-hidden="true"><Icon name="network"/></div></div></section>
 <section className="section insights-preview"><div className="container insights-preview-layout"><div data-reveal><Label number="09">Insights & Events</Label><h2>Connections<br/>in practice.</h2></div><div className="insights-preview-copy" data-reveal><p>Business meetings, networking, thematic events, international initiatives and business missions connecting Poland and Israel.</p><TextLink href="/insights">View all insights & events</TextLink></div></div></section>
 <Closing title="Let’s talk business." text="Tell us what you are looking to achieve in Poland, Israel or between the two markets." button="Send an enquiry"/>
</>}
