'use client';
import {useEffect,useRef,useState,type FormEvent} from 'react';
import Link from 'next/link';
import {topics} from '@/content/site';
import {Icon} from './ui';
export function ContactForm({polish=false}:{polish?:boolean}){
 const form=useRef<HTMLFormElement>(null);const summary=useRef<HTMLDivElement>(null);
 const [topic,setTopic]=useState('');const [values,setValues]=useState<Record<string,string>|null>(null);
 useEffect(()=>{const value=new URLSearchParams(window.location.search).get('topic');if(value&&topics.includes(value))setTopic(value);},[]);
 function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();const data=Object.fromEntries(new FormData(event.currentTarget).entries()) as Record<string,string>;setValues(data);requestAnimationFrame(()=>summary.current?.focus());}
 const t=polish?{title:'Tytuł',selectTitle:'Wybierz tytuł',first:'Imię',last:'Nazwisko',company:'Firma',position:'Stanowisko',email:'Adres e-mail',phone:'Telefon',country:'Kraj',topic:'W czym możemy pomóc?',selectTopic:'Wybierz obszar wsparcia',objective:'Opowiedz nam o swoim celu biznesowym',placeholder:'Opisz rynek, branżę i rodzaj kontaktu, którego szukasz…',consent:'Wyrażam zgodę na kontakt w sprawie tego zapytania i zapoznałem(-am) się z informacją o prywatności.',previewNote:'Podgląd wersji roboczej: formularz pozwala lokalnie sprawdzić treść zapytania. Dane nie są wysyłane ani zapisywane. Przed uruchomieniem zostaną dodane zatwierdzone informacje o prywatności i bezpieczna wysyłka wiadomości.',preview:'Podgląd zapytania',summary:'Podgląd Twojego zapytania',notSent:'Wiadomość nie została wysłana. Możesz edytować pola i ponownie wyświetlić podgląd.',name:'Imię i nazwisko',area:'Temat',unspecified:'Nie określono'}:{title:'Title',selectTitle:'Select title',first:'First name',last:'Last name',company:'Company',position:'Position',email:'Email address',phone:'Telephone',country:'Country',topic:'What can we help you with?',selectTopic:'Select an area of support',objective:'Tell us about your business objective',placeholder:'Your market, sector, and the type of connection you are looking for…',consent:'I agree to be contacted about this enquiry and acknowledge the privacy information.',previewNote:'Draft preview: this form lets you review an enquiry locally. It does not send or save your details. PICC’s final privacy wording and secure email delivery will be connected before launch.',preview:'Preview enquiry',summary:'Your enquiry preview',notSent:'Nothing has been sent. You can edit the fields above and preview again.',name:'Name',area:'Area',unspecified:'Not specified'};
 const translatedTopics:Record<string,string>={'Business Partner Search':'Wyszukiwanie partnerów biznesowych','Market Entry':'Wejście na rynek','Business Meeting':'Spotkanie biznesowe','Business Mission':'Misja gospodarcza','International Project':'Projekt międzynarodowy','Startup / Innovation':'Startup / Innowacje','Investor Connection':'Kontakt z inwestorem','Institutional Contact':'Kontakt instytucjonalny','Other':'Inne'};
 return <div data-reveal="right"><div className="form-intro"><h2>{polish?'Twój cel biznesowy':'Your business objective'}</h2><span>{polish?'* Pola wymagane':'* Required fields'}</span></div><form className="contact-form" ref={form} onSubmit={submit}>
 <div className="field"><label htmlFor="title">{t.title}</label><select id="title" name="title" defaultValue=""><option value="">{t.selectTitle}</option><option>{polish?'Pan':'Mr.'}</option><option>{polish?'Pani':'Ms.'}</option>{!polish&&<option>Mrs.</option>}</select></div><div className="field"><label htmlFor="firstName">{t.first} <span className="required">*</span></label><input id="firstName" name="firstName" autoComplete="given-name" required maxLength={100}/></div>
 <div className="field"><label htmlFor="lastName">{t.last} <span className="required">*</span></label><input id="lastName" name="lastName" autoComplete="family-name" required maxLength={100}/></div><div className="field"><label htmlFor="company">{t.company} <span className="required">*</span></label><input id="company" name="company" autoComplete="organization" required maxLength={180}/></div>
 <div className="field"><label htmlFor="position">{t.position}</label><input id="position" name="position" autoComplete="organization-title" maxLength={150}/></div><div className="field"><label htmlFor="email">{t.email} <span className="required">*</span></label><input id="email" name="email" type="email" autoComplete="email" required maxLength={254}/></div>
 <div className="field"><label htmlFor="telephone">{t.phone}</label><input id="telephone" name="telephone" type="tel" autoComplete="tel" maxLength={40}/></div><div className="field"><label htmlFor="country">{t.country}</label><input id="country" name="country" autoComplete="country-name" maxLength={100}/></div>
 <div className="field field-wide"><label htmlFor="topic">{t.topic}</label><select id="topic" name="topic" value={topic} onChange={e=>setTopic(e.target.value)}><option value="">{t.selectTopic}</option>{topics.map(x=><option key={x} value={x}>{polish?translatedTopics[x]:x}</option>)}</select></div>
 <div className="field field-wide"><label htmlFor="objective">{t.objective} <span className="required">*</span></label><textarea id="objective" name="objective" required minLength={10} maxLength={5000} placeholder={t.placeholder}/></div>
 <label className="consent field-wide"><input name="consent" type="checkbox" required/><span>{t.consent} <Link href={polish?'/pl/privacy':'/privacy'}>{polish?'Szczegóły':'Details'}</Link>. <span className="required">*</span></span></label>
 <p className="form-preview-note field-wide">{t.previewNote}</p>
 <div className="field-wide"><button type="submit" className="button"><span>{t.preview}</span><Icon name="arrow-up-right"/></button></div>
 {values&&<div className="review-summary" ref={summary} tabIndex={-1} role="status"><h3>{t.summary}</h3><p style={{fontSize:14,marginBottom:20}}>{t.notSent}</p><dl><dt>{t.name}</dt><dd>{values.firstName} {values.lastName}</dd><dt>{t.company}</dt><dd>{values.company}</dd><dt>{t.email}</dt><dd>{values.email}</dd><dt>{t.area}</dt><dd>{topic?(polish?translatedTopics[topic]??topic:topic):t.unspecified}</dd><dt>{t.objective}</dt><dd>{values.objective}</dd></dl></div>}
 </form></div>;
}
